### ISSUE TITLE
Save set of rules into presets

### ISSUE THREAD

**Issue by itsdmd** [itsdmd/CS202-Final#2]

**Comment by itsdmd** [comment]
Use JSON format. (Improvement No.2)

Example:
```json
{ "Name" : "AddPrefix", "Config" : "XYZ" },
{ "Name" : "OneSpace", "Config" : "" }
```

**Comment by itsdmd** [comment]
Should make a new class named `PresetProcessor` contains 2 functions: `ReadPresetFile` and `WritePresetFile`.

For this issue, just implement the `WritePresetFile`. This function will take in a `List<IRule>` and save it to a `.json` file.

**Comment by itsdmd** [comment]
Create a button to perform saving action called `saveRulePresetButton`.

This button when clicked should call a `SaveFileDialog` (see [this](https://wpf-tutorial.com/dialogs/the-savefiledialog/)) and save the file to the specified directory.

**Comment by itsdmd** [comment]
> Create a button to perform saving action called `saveRulePresetButton`.

Created in 8de5dbd7c7c4bfc4cdb9a3fc4f76dc0f3463ba64. Not yet implemented.

**Comment by soleilmeo** [comment]
Since we're going to add JSON as additional improvement, we should support both `.txt` (raw rule preset file) loading and `.json` (widely supported, easy-to-read formatting) saving and loading.

**Comment by itsdmd** [comment]
> Since we're going to add JSON as additional improvement, we should support both `.txt` (raw rule preset file) loading and `.json` (widely supported, easy-to-read formatting) saving and loading.

Agree. Updated #27.
